<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  #%L
  Kommunalportal.NRW Extension-API
  %%
  Copyright (C) 2018 - 2021 SIT GmbH
  %%
  © SIT Südwestfalen-IT – alle Rechte vorbehalten
  #L%
  -->

<wsdl:definitions name="MessageBoxService" targetNamespace="urn:kommunalportal-nrw:extension-api:K1.0:MessageBox:Service"
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
				  xmlns:mbs="urn:kommunalportal-nrw:extension-api:K1.0:MessageBox:Service">
	<wsdl:import location="MessageBoxService.wsdl" namespace="urn:kommunalportal-nrw:extension-api:K1.0:MessageBox:Service" />
	<wsdl:service name="MessageBox">
		<wsdl:port binding="mbs:MessageBoxServiceSOAP" name="MessageBoxServiceSOAP">
			<soap:address location="https://portal-api.citkomm.de/Remote/K1.0/MessageBoxService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
