<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  #%L
  Kommunalportal.NRW Extension-API
  %%
  Copyright (C) 2018 - 2021 SIT GmbH
  %%
  © SIT Südwestfalen-IT – alle Rechte vorbehalten
  #L%
  -->

<wsdl:definitions name="ChatService" targetNamespace="urn:kommunalportal-nrw:extension-api:K1.0:Chat:Service"
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
				  xmlns:cts="urn:kommunalportal-nrw:extension-api:K1.0:Chat:Service">
	<wsdl:documentation>
		Der Chat-Endpunkt bietet Methoden für die Interaktion mit dem Portalchat.
		Dadurch können beliebige Nachrichten zwischen den Benutzern der Extension über citkoPortal ausgetauscht werden.
	</wsdl:documentation>
	<wsdl:import location="ChatService.wsdl" namespace="urn:kommunalportal-nrw:extension-api:K1.0:Chat:Service" />
	<wsdl:service name="Chat">
		<wsdl:port binding="cts:ChatServiceSOAP" name="ChatServiceSOAP">
			<soap:address location="https://portal-api.citkomm.de/Remote/K1.0/ChatService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
